function value = cudaInfo()
%CUDAINFO Describe CUDA support in this CPU-only MATLAB distribution.
value = struct( ...
    "Status", "unavailable", ...
    "Compiled", false, ...
    "Available", false, ...
    "DiagnosticOnly", false, ...
    "DeviceCount", 0, ...
    "RuntimeVersion", missing, ...
    "DriverVersion", missing, ...
    "NoCpuFallback", true);
end
