function output = pls(Xtrain, Ytrain, Xtest, options)
%PLS Fit a fastPLS model and optionally predict independent observations.
arguments
    Xtrain
    Ytrain
    Xtest = []
    options.NumComponents = 2
    options.Method = "simpls"
    options.Classifier = ""
    options.Scaling = "centering"
    options.Backend = "cpu"
    options.Oversample = 32
    options.Power = 5
    options.Seed = 1
    options.OrthogonalComponents = 1
    options.Kernel = "linear"
    options.Gamma = []
    options.Degree = 3
    options.Offset = 1
    options.StoreScores = false
    options.YTest = []
    options.Top = []
    options.ByColumn (1, 1) logical = false
end
model = fastpls.Model( ...
    NumComponents=options.NumComponents, ...
    Method=options.Method, ...
    Classifier=options.Classifier, ...
    Scaling=options.Scaling, ...
    Backend=options.Backend, ...
    Oversample=options.Oversample, ...
    Power=options.Power, ...
    Seed=options.Seed, ...
    OrthogonalComponents=options.OrthogonalComponents, ...
    Kernel=options.Kernel, ...
    Gamma=options.Gamma, ...
    Degree=options.Degree, ...
    Offset=options.Offset, ...
    StoreScores=options.StoreScores);
model.fit(Xtrain, Ytrain);
if isempty(Xtest)
    output = model;
else
    prediction = model.predict(Xtest, Top=options.Top);
    output = struct("Model", model, "Prediction", prediction);
    if ~isempty(options.YTest)
        if isempty(model.Classes)
            output.Metrics = fastpls.evaluate( ...
                options.YTest, prediction, YTrain=Ytrain, ...
                ByColumn=options.ByColumn);
        else
            output.Metrics = fastpls.evaluate( ...
                string(options.YTest), string(prediction), ...
                ByColumn=options.ByColumn);
        end
    end
end
end
