function build_fastpls()
%BUILD_FASTPLS Compile the native fastPLS MATLAB interface.
root = fileparts(mfilename("fullpath"));
source = fullfile(root, "src");
include = fullfile(root, "vendor", "fastpls", "include");
arguments = { ...
    "-R2018a", ...
    "-output", fullfile(root, "fastpls_mex"), ...
    "-I" + source, ...
    "-I" + include, ...
    fullfile(source, "fastpls_mex.cpp"), ...
    fullfile(source, "native_backend.cpp")};
if ismac
    arguments = [{ ...
        "CXXFLAGS=$CXXFLAGS -std=c++17 -O3 -DFASTPLS_MATLAB_ACCELERATE=1", ...
        "LDFLAGS=$LDFLAGS -framework Accelerate"}, arguments];
elseif isunix
    arguments = [{ ...
        "CXXFLAGS=$CXXFLAGS -std=c++17 -O3", ...
        "LDFLAGS=$LDFLAGS -lopenblas"}, arguments];
else
    arguments = [{"COMPFLAGS=$COMPFLAGS /std:c++17 /O2"}, arguments];
end
mex(arguments{:});
fprintf("Built %s using %s.\n", mexext, fastpls.backendInfo());
end
